"""first migr

Revision ID: 47ba6f2499dd
Revises: 5c675ab24529
Create Date: 2024-03-27 09:05:17.960034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ba6f2499dd'
down_revision: Union[str, None] = '5c675ab24529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact2', sa.String(), nullable=False))
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'contact2')
    # ### end Alembic commands ###
