"""first migr

Revision ID: dbd702a9854b
Revises: 451c4d2ea366
Create Date: 2024-03-27 09:08:30.620967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd702a9854b'
down_revision: Union[str, None] = '451c4d2ea366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact3', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact3')
    # ### end Alembic commands ###
